export const FETCH_FEEDS_REQUESTED = 'FETCH_FEEDS_REQUESTED';
export const FETCH_FEEDS_SUCCEEDED = 'FETCH_FEEDS_SUCCEEDED';
export const FETCH_FEEDS_FAILED = 'FETCH_FEEDS_FAILED';
export const ADD_COMMENT_REQUESTED = 'ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_SUCCEEDED = 'ADD_COMMENT_SUCCEEDED';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';
export const ADD_LIKE_REQUESTED = 'ADD_LIKE_REQUESTED';
export const ADD_LIKE_SUCCEEDED = 'ADD_LIKE_SUCCEEDED';
export const ADD_LIKE_FAILED = 'ADD_LIKE_FAILED';
export const PROFILE_REQUESTED = 'PROFILE_REQUESTED';
export const PROFILE_SUCCEEDED = 'PROFILE_SUCCEEDED';
export const PROFILE_FAILED = 'PROFILE_FAILED';

